language: clojure
lein: lein2
script: lein2 do clean, javac, test :all
jdk:
- openjdk7
- oraclejdk7
- oraclejdk8
before_script:
- cp test/resources/ctia-test.properties.ci resources/ctia-default.properties
- until curl http://localhost:9200/; do sleep 1; done
services:
- elasticsearch
notifications:
  hipchat:
    rooms:
      secure: j4t8UR8PVhiZJRdU6wU8obaC7rot6I47zS157eT7yq8ucYwjiN8Brdwy7xoPvM63vS+XVNHYOJnZdDxzcUtbuAFDv9Fnu2IO2E9Srm7dYusCRay17DwMqESrt3kpRrXXGaC05GJjS+VDJiAHzmM0DDXT0gxV+Yw6Lw10c7iNQDp8RNSJN+IlbTcNsOgMSFitP5I43Y8S2w4aCmG15VxhwfrAjeRqG9tmN9SGmYdcRJzQC7M2B0AgpaQqbjrQCN3vzsB+r3TyPFCkSZHxogcm3IUKBMVAo+HFOuIxaifOJ4MlOGgIEwD5w8RfjB7O8JP/zT675ggCOMVVPxfhwxz5v5+ofIe4cVuYKLOwcvnCjDC9gx4BxSJcJnWpiDOraXGs2Cu21dDx0Vww4uPZqmgNOcZWmvATgPeKpUWyW+aa8Yq1++9hDRjVTYACrfGNFXdz7UBRKDXiA1YnFXs0O+g1qs9YSq/IEiVgBqzJ14NupS+iSqRQAPxPyOId5O6ZI9tMfzymzKLPrGcLswOTpH/ZAjN4eLssCTh9MmsXYpEftAoo5VfG3aEbUSRoU80HgFYw8joqRTXTmBpnrMYpkLta9Lht7Ihs/+qjFCqfdayXr53dZkASia3opg7DZz6kVLq09rj5Iw6Y4TVQPIralblMbre7bxS2xD6ZB3Vzz/o4VQM=
    on_success: always
    on_failure: change
